name: iOS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Run Tests
      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme DVTWeatherApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest'

      # Step 3: Build App
      - name: Build App
        run: |
          xcodebuild build \
            -scheme DVTWeatherApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -configuration Release
